services:
  sonarqube:
    image: $SONARQUBE_VERSION
    # image: registry.$DOMAIN_NAME/sonarqube
    # build:
    #   context: .
    #   args: 
    #     SONARQUBE_VERSION:
    restart: always
    ports:
      - 9000
      - 9002
    volumes:
      - data:/opt/sonarqube/data
      - logs:/opt/sonarqube/logs
      - extensions:/opt/sonarqube/extensions
    hostname: sonarqube.$DOMAIN_NAME
    networks:
      - cicd
    labels:
      traefik.enable: true
      traefik.http.routers.sonarqube.entrypoints: web
      traefik.http.routers.sonarqube.rule: Host(`sonarqube.$DOMAIN_NAME`)
      traefik.http.routers.sonarqube.service: sonarqube
      traefik.http.services.sonarqube.loadbalancer.server.port: 9000
      traefik.http.routers.sonarqube-ssl.entrypoints: websecure
      traefik.http.routers.sonarqube-ssl.rule: Host(`sonarqube.$DOMAIN_NAME`)
      traefik.http.routers.sonarqube-ssl.service: sonarqube
      traefik.http.services.sonarqube-ssl.loadbalancer.server.port: 9000
      traefik.http.routers.sonarqube-ssl.tls: true
volumes:
  data:
  logs:
  extensions:
networks:
  cicd:
    external: true # name: cicd
