services:
  traefik:
    image: $TRAEFIK_VERSION
    # image: registry.$DOMAIN_NAME/traefik
    # build:
    #   context: .
    #   args: 
    #     TRAEFIK_VERSION:
    #     DOMAIN_NAME:
    restart: always
    networks:
      - cicd
    ports:
      - '8080:8080'
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - ./etc/traefik.yml:/etc/traefik/traefik.yml
      - ./etc/config.yml:/etc/traefik/config.yml
      - ./certs/$DOMAIN_NAME.crt:/etc/certs/$DOMAIN_NAME.crt
      - ./certs/$DOMAIN_NAME.key:/etc/certs/$DOMAIN_NAME.key
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # labels:
    #   traefik.enable: true
    #   traefik.http.routers.traefik: true
volumes:
  data:
networks:
  cicd:
    external: true # name: cicd
